# Generated by Django 4.2.3 on 2024-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Title', models.CharField(max_length=100)),
                ('Movie_Season', models.CharField(blank=True, max_length=15)),
                ('Movie_Episode', models.CharField(blank=True, max_length=15)),
                ('Movie_Body', models.TextField(max_length=350)),
                ('Movie_Date', models.DateField(auto_now_add=True)),
                ('Movie_Trailer', models.CharField(max_length=1000)),
                ('Movie_Type', models.CharField(max_length=350)),
                ('Movie_Download_Link', models.CharField(max_length=1000)),
                ('Movie_Img', models.ImageField(default=' ', upload_to='images')),
                ('Movie_views', models.IntegerField(default=0)),
                ('Movie_Tag', models.ManyToManyField(to='Netblog.movie_tag')),
            ],
        ),
    ]
