# Generated by Django 4.2.3 on 2024-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netblog', '0002_movie_movie_subtitle_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_Subtitle_Download_Link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
