# Generated by Django 4.2.3 on 2024-04-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Netblog', '0003_alter_movie_movie_subtitle_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=15)),
                ('episode_number', models.IntegerField()),
                ('movie_body', models.TextField(max_length=350)),
                ('date', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='Netblog.movie')),
            ],
        ),
    ]
