# Generated by Django 4.2.3 on 2024-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netblog', '0004_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='season',
            new_name='Episode',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='movie_body',
        ),
        migrations.AddField(
            model_name='episode',
            name='Season',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
