# Generated by Django 4.2.3 on 2024-08-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netblog', '0006_remove_episode_title_episode_download_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
    ]
